version: "3.8"

services:
  backend:
    build:
      context: ../backend-python-downloader
    container_name: backend-downloader
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ../frontend-nextjs
    container_name: frontend-nextjs
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
